"""empty message

Revision ID: 73e87efe0cdf
Revises: 
Create Date: 2024-07-24 17:35:16.686555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e87efe0cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_name'), ['name'], unique=False)

    op.create_table('book_data',
    sa.Column('book_data_id', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.String(length=255), nullable=False),
    sa.Column('bookshelves', sa.String(length=255), nullable=False),
    sa.Column('copyright', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('book_data_id')
    )
    op.create_table('creations',
    sa.Column('creation_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('meta_data_used', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('creation_id')
    )
    op.create_table('line_fetched',
    sa.Column('line_fetched_id', sa.Integer(), nullable=False),
    sa.Column('book_data_id', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_data_id'], ['book_data.book_data_id'], ),
    sa.PrimaryKeyConstraint('line_fetched_id')
    )
    op.create_table('line_stamped',
    sa.Column('line_stamped_id', sa.Integer(), nullable=False),
    sa.Column('creation_id', sa.Integer(), nullable=False),
    sa.Column('line_fetched_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creation_id'], ['creations.creation_id'], ),
    sa.ForeignKeyConstraint(['line_fetched_id'], ['line_fetched.line_fetched_id'], ),
    sa.PrimaryKeyConstraint('line_stamped_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_stamped')
    op.drop_table('line_fetched')
    op.drop_table('creations')
    op.drop_table('book_data')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_name'))

    op.drop_table('artists')
    # ### end Alembic commands ###
